name: mucke
description: music player
publish_to: none

version: 1.5.1+12

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  async_task: ^1.0.20
  audio_service: ^0.18.7  # MIT
  audio_session: ^0.1.5  # MIT
  collection: ^1.17.1  # BSD 3
  device_info_plus: ^9.0.2  # BSD 3
  drift: ^2.9.0  # MIT
  equatable: ^2.0.3  # MIT
  file_picker: ^5.3.2  # MIT
  fimber: ^0.7.0  # Apache 2.0
  fimber_io: ^0.7.0  # Apache 2.0
  flutter:
    sdk: flutter
  flutter_fimber: ^0.7.0  # Apache 2.0
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.0  # MIT
  flutter_speed_dial: ^7.0.0  # MIT
  get_it: ^7.1.3  # MIT
  image: ^4.0.17
  intl: any
  just_audio: ^0.9.18  # MIT
  metadata_god:
    git:
      url: https://github.com/nedmv/metadata_god.git
      rev: HEAD
      path: packages/metadata_god
  mobx: 2.1.3  # MIT
  optimization_battery: ^0.0.7  # MIT
  package_info_plus: ^4.0.1
  page_indicator_plus: ^1.0.3  # MIT
  path: ^1.8.0  # BSD 3
  path_provider: ^2.0.2  # BSD 3
  permission_handler: ^10.2.0  # MIT
  provider: ^6.0.2  # MIT
  reorderables: ^0.6.0  # MIT
  share_plus: ^7.0.2
  sqlite3_flutter_libs: ^0.5.0  # MIT
  string_similarity: ^2.0.0  # MIT
  text_scroll: ^0.2.0  # MIT

dev_dependencies:
  build_runner: ^2.4.6  # BSD 3
  drift_dev: ^2.5.0  # MIT
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1+3  # MIT
  mockito: ^5.4.2
  test: ^1.24.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true  # added for l10n

  uses-material-design: true
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family:  MuckeIcons
      fonts:
        - asset: fonts/MuckeIcons.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
