# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    env:
      KEYSTORE_GITHUB: ${{ secrets.KEYSTORE_GITHUB }}
      KEY_PROPERTIES_GITHUB: ${{ secrets.KEY_PROPERTIES_GITHUB }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v2
      with:
        java-version: '12.x'
        distribution: 'zulu'
    - run: echo $KEYSTORE_GITHUB | base64 -d > android/github.jks
    - run: echo $KEY_PROPERTIES_GITHUB | base64 -d > android/key.properties
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.x'
    - run: flutter pub get
    - if: startsWith(github.ref, 'refs/tags')
      run: flutter build apk --flavor github
    - if: ${{ !startsWith(github.ref, 'refs/tags') }}
      run: flutter build apk --profile --flavor dev
    - name: Upload a Release Artifact
      uses: actions/upload-artifact@v4
      if: startsWith(github.ref, 'refs/tags')
      with:
        path: src/build/app/outputs/flutter-apk/app-github-release.apk
    - name: Upload a Dev Artifact
      uses: actions/upload-artifact@v4
      if: ${{ !startsWith(github.ref, 'refs/tags') }}
      with:
        path: src/build/app/outputs/flutter-apk/app-dev-profile.apk
    - name: Github Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags')
      with:
        files: src/build/app/outputs/flutter-apk/app-github-release.apk
